### ISSUE TITLE
Wrong documentation for adding new Validation

### ISSUE THREAD

**Issue by ivandoric** [ricardojoaomestre/js-vanilla-form-validation#1]
Hi,

I'm trying out this validator and so far it's really nice. The problem I ran in is in your documentation for adding custom validation. In the docs it says:

`this.validator.addCustomValidation(input, 'blur', myCustomValidation);`

But actually it should be:

`this.validator.addCustomValidation(input, myCustomValidation, 'blur');`

I had to read the source to figure it out. 

Hope this helps someone.

**Comment by ricardojoaomestre** [comment]
You're right! Thank you for noticing. Fixed it!
